---
title: "Experiment2.1"
author: "Eliyahu Addess"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here we shift. mod1=parsim, mod2 = underfit, mod3=false, mod4 = overfit.

```{r message=FALSE, warning=FALSE}
# load libraries
library(tidyverse)
library(future.apply) #parallel processing
library(tictoc) #timing code
library(knitr) #tables

#load functions
source("ProjectFunctions.R")

# set up parallel processing
plan(multisession)

# set seed for reproducibility
set.seed(42)

# load data
data <- read.csv("data_generic.csv")
```


```{r}
# fit base model
mod1 <- lm(y~x1+ x2 + x3 +x4 +x5 +x6 +x7 +x8 +x9, data = data)
coefs1 <- unname(mod1$coefficients)
```


```{r message=FALSE, warning=FALSE}
# simulation
MC2.1 <- as.data.frame(t(future_replicate(1000, 
                                          experiment2(sd = 10000, data = data),
                                          future.seed = TRUE)))
```


```{r}
#results
histo(MC2.1,title =  "MC2.1")

kable(props(MC2.1))
```

